scripts/artifacts-gyp.mjs
=> Delete prebuilds folder and create it when packing

index.d.ts, scripts/crawler.js, src/lib.rs, src/rewriter.rs, src/tests/binary_assignation_test.rs, src/tests/mod.rs, src/tests/source_map_test.rs, src/tests/string_method_test.rs, src/transform/call_expr_transform.rs, src/visitor/block_transform_visitor.rs, src/visitor/csi_methods.rs, src/visitor/ident_provider.rs, src/visitor/visitor_util.rs, test/binary_expression.spec.js, test/rewriter_config.spec.js, test/string_method.spec.js, test/util.js
=> Include callee as argument in rewritten CSI methods

main.js, package-lock.json, package.json, test/main.spec.js
Returns a dummy Rewriter if an exception occurs when loading native addon
=> dummy rewriter

js/source-map/index.js, main.js, package-lock.json, package.json, test/stack_trace.spec.js
Cache the sourcemaps generated on rewrite the file
We have to fix the stacktraces
=> Fix stacktraces

.eslintrc.json, .github/workflows/build.yml, integration-test/.eslintrc.json, integration-test/edited-files-cache.js, integration-test/requires/errors.js, integration-test/setup.js, integration-test/stack-traces.spec.js, js/source-map/index.js, js/stack-trace/index.js, package-lock.json, package.json
Fix the stack traces in error
It wasing working correctly
=> Fix stack traces in general errors

Cargo.lock, Cargo.toml, package-lock.json, package.json
Update main branch version to 2.0.0-pre, 1.0 is already in it own branch
=> Update version to 2.0.0-pre

.github/workflows/build-wasm.yml, package-lock.json
=> Prepare 1.0.0 release

src/transform/call_expr_transform.rs, src/visitor/csi_methods.rs, test/string_method.spec.js, test/util.js
=> Rewrite some methods like concat or replace when callers are literals

Cargo.lock, Cargo.toml, package-lock.json, package.json, src/transform/call_expr_transform.rs, src/visitor/csi_methods.rs, test/string_method.spec.js, test/util.js
=> Release 1.1.1

Cargo.lock, Cargo.toml, js/source-map/index.js, package-lock.json, package.json, test/stack_trace.spec.js
=> Release 1.1.2

Cargo.lock, Cargo.toml, package-lock.json, package.json, src/lib_napi.rs, src/lib_wasm.rs, src/rewriter.rs, src/tests/mod.rs, src/tests/source_map_test.rs, src/tests/string_method_test.rs
* Fix an issue in expressions with values containing `//# sourceMappingURL` (#46)
=> Release 2.0.1

.github/workflows/release.yml, .npmignore, Cargo.lock, Cargo.toml, LICENSE-3rdparty.csv, index.d.ts, index.js, js/source-map/index.js, main.js, package-lock.json, package.json, src/lib.rs, src/lib_napi.rs, src/lib_wasm.rs, src/rewriter.rs, src/tests/mod.rs, src/tests/source_map_test.rs, src/tracer_logger.rs, src/util.rs, src/visitor/csi_methods.rs, test/rewriter_config.spec.js, test/tracer_logger.spec.js, test/util.js, tracer_logger.js
-  Wasm sourcemap chaining #50 
-  Allow configure a custom js logger #51
=> Release 2.0.2

Cargo.lock, Cargo.toml, package-lock.json, package.json
=> Upgrade to version 2.1.0

Cargo.lock, Cargo.toml, package-lock.json, package.json
Release 2.1.1
- https://github.com/DataDog/dd-native-iast-rewriter-js/pull/58
=> Release 2.1.1

.github/workflows/build-wasm.yml, Cargo.lock, Cargo.toml, docker/v8test-builder.Dockerfile, package-lock.json, package.json
- Fix wasm-pack@0.10.3 as performance regression workaround
- Reduce v8 test docker image size 
- Upgrade version to 2.1.2
=> Upgrade to version 2.1.2

.github/workflows/release.yml
Fix wasm-pack version in release workflow
=> wasm-pack@0.10.3 in release workflow

Cargo.lock, Cargo.toml, package-lock.json, package.json
=> Release 2.1.3

.github/workflows/release.yml
Enable package distribution signing, adding provenance option to npm publish in the CI publish action.
Improve supply chain security
=> Add provenance option to npm publish

Cargo.lock, Cargo.toml, README.md, package-lock.json, package.json
=> Release 2.2.0

Cargo.lock, Cargo.toml, package-lock.json, package.json
=> Release 2.2.1

Cargo.lock, Cargo.toml, package-lock.json, package.json
=> Release 2.2.2

Cargo.lock, Cargo.toml, package-lock.json, package.json
=> Release 2.2.3

Cargo.lock, Cargo.toml, LICENSE-3rdparty.csv, src/tests/binary_assignation_test.rs, src/tests/binary_expression_test.rs, src/tests/literal_test.rs, src/tests/source_map_test.rs, src/tests/string_method_test.rs, src/tests/telemetry_test.rs, src/tests/template_literal_test.rs, src/transform/function_prototype_transform.rs, src/visitor/block_transform_visitor.rs
- Replace `spectral` dev dependency with `speculoos` because the former doesn't compile with newer rustc versions.
- Fix clippy complaints
=> Rustc update changes

Cargo.lock, Cargo.toml, package-lock.json, package.json
=> Release 2.3.0

Cargo.lock, Cargo.toml, package-lock.json, package.json
=> Release 2.3.1

Cargo.lock, Cargo.toml, package-lock.json, package.json
=> Release 2.4.0

Cargo.lock, Cargo.toml, package-lock.json, package.json
=> Release 2.4.1

.github/workflows/build-wasm.yml, Cargo.lock, Cargo.toml, LICENSE-3rdparty.csv, scripts/crawler.js, src/rewriter.rs, src/tracer_logger.rs, src/transform/assign_add_transform.rs, src/transform/binary_add_transform.rs, src/transform/call_expr_transform.rs, src/transform/function_prototype_transform.rs, src/transform/operand_handler.rs, src/transform/template_transform.rs, src/visitor/block_transform_visitor.rs, src/visitor/ident_provider.rs, src/visitor/literal_visitor.rs, src/visitor/operation_transform_visitor.rs, src/visitor/visitor_util.rs
- Upgrade swc version
- Include a summary of the v8 tests that rewriter could not rewrite due to js syntax errors or unsupported js features. [Example](https://github.com/DataDog/dd-native-iast-rewriter-js/actions/runs/10145491394/attempts/1#summary-28051671806)
=> Upgrade swc version

src/tests/binary_expression_test.rs, src/visitor/operation_transform_visitor.rs
Avoid overriding a previous Modified status if some expression are not transformed
=> do not override a Modified or Cancelled status

Cargo.lock, Cargo.toml, package-lock.json, package.json
Release 2.5.0
Upgraded swc version, support spread operator, better template literal rewriting.
=> Release 2.5.0

src/lib_wasm.rs, src/rewriter.rs, src/visitor/block_transform_visitor.rs
=> keep lib_wasm swc agnostic

Cargo.lock, Cargo.toml, package-lock.json, package.json
Prepare 2.6.1 release
Include the fix for #101
=> Release 2.6.1

Cargo.lock, Cargo.toml, package-lock.json, package.json
=> Release 2.7.0

Cargo.toml, package.json
Applies some build optimizations to improve the binary file size and performance.
=> Reducing binary file size

Cargo.lock, Cargo.toml
Right now, the main branch contains incompatible commits, so we need to pin it.
=> pin orchestrion-js
