DataDog/dd-wasm-js-rewriter

.github/workflows/build.yml, .husky/pre-push, package.json
Keeps the current integration test script to be run in CI and adds a new one to be run in local which outputs the results in the stdout.
Add a new step in pre push hook to run integration test.
No results were displayed when running integration test.
=> Organize integration test

js/source-map/index.js, js/stack-trace/index.js, test/stack_trace.spec.js
Adds new argument to `getPrepareStackTrace` function to filter out sourceMap files searching
=> Filter sourcemap searching

src/lib_napi.rs, src/lib_wasm.rs, src/rewriter.rs, src/tests/mod.rs, src/tests/source_map_test.rs, src/tests/string_method_test.rs
Save original sourceMap comment for later processing and replace sourceMap expression only if found before.
Avoid errors in javascript files with expressions containing `//# sourceMap` text
=> Fix sourceMap comment replacement

LICENSE-3rdparty.csv, js/source-map/index.js, main.js, package-lock.json, package.json, test/resources/stacktrace-sourcemap/test-min.min.js, test/stack_trace.spec.js
Exports a new method called `getOriginalPathAndLine` in charge of read from disk a javascript file, check if it contains a sourceMapping, parse or load it and search the corresponding token to the line and column passed as arguments.
If line and column are found it will return an object with the path, line and column in the original source file.
When IAST detects a vulnerability, it contains the location (file and line) where the vulnerability has been found. If the file points to a source file, like in the case of a transpiled typescript or minimized js files, we can resolve the vulnerability location to the original source file.
=> Find path and line using original sourcemap

index.d.ts, index.js, main.js, src/lib_napi.rs, src/lib_wasm.rs, src/rewriter.rs, src/tracer_logger.rs
Changes the way logger is initialized
Seems that logger initialization is a bit of a heavy operation so this PR removes the automatic initialization and only initializes the logger when it is enabled by configuration.
=> Remove init method and initialize logger only if configured

src/visitor/literal_visitor.rs, test/literals.spec.js
Fixes a problem with calls to new RegExp with no arguments :S
=> Check if new RegExp has arguments

index.d.ts, js/source-map/index.js, main.js, scripts/crawler.js, src/lib_napi.rs, src/lib_wasm.rs, test/main.spec.js, test/rewriter_config.spec.js
- Avoid reading sourceMaps if source file has not been modified
- Catch errors produced when reading sourceMap files
All rewritten source files have the sourceMap inlined so when the source file is not modified and it originally contained a sourceMappingUrl pointing to a sourceMap file we try to read it. If the sourceMap file doesn't exist or we don't have permissions to read it an Error is thrown reaching the tracer and producing a telemetry log.
=> Avoid reading sourceMaps for unmodified source files and catch errors if any

js/stack-trace/index.js, main.js
Export `kSymbolPrepareStackTrace` & protect `wrappedPrepareStackTrace` path
Be able to check the `kSymbolPrepareStackTrace` symbol in the iast part to ensure it has wrapped the `prepareStrackTrace` function before reset it.
=> Export kSymbolPrepareStackTrace

scripts/crawler.js, src/tests/string_method_test.rs, src/transform/call_expr_transform.rs
Rewrite call expressions (of configured methods like join, slice, concat) where member is an array
Rewrite [str1, str2].join()
=> Rewrite [str1, str2].join() calls

Cargo.lock, index.d.ts, scripts/crawler.js, src/lib_napi.rs, src/lib_wasm.rs, src/tests/mod.rs, src/tracer_logger.rs, src/transform/call_expr_transform.rs, src/visitor/csi_methods.rs, src/visitor/visitor_util.rs, test/method_without_callee.spec.js, test/util.js
Support rewriting methods without callee, like `method(param)`  instead of `obj.method(param)`. 
Are methods that we want to instrument with rewriter that can be used without callee, like `eval`
=> Support rewrite on methods without callee

src/transform/template_transform.rs, test/template_literal.spec.js
Fixes some corner cases when template literals are used with numbers
Fix the bugs
=> Fix template literals with numbers

.github/workflows/build-wasm.yml, .github/workflows/build.yml, .github/workflows/release.yml
Set `contents: write` permission in `create_release` job
Set `checks: write` for `mikepenz/action-junit-report` action
After changing the default workflow permissions in the repo, it is necessary to adjust the permissions in the workflow file.
[Create release endpoint doc](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release)
=> Set GITHUB_TOKEN permissions for create_release job in release workflow

src/tests/string_method_test.rs, src/transform/call_expr_transform.rs, src/transform/operand_handler.rs, src/visitor/ident_provider.rs, test/string_method.spec.js
Do not use an ident for literals
=> Do not use an ident for literals

docker/v8test.Dockerfile, src/tests/string_method_test.rs, src/transform/call_expr_transform.rs, src/transform/function_prototype_transform.rs, src/transform/operand_handler.rs, src/visitor/ident_provider.rs, test/string_method.spec.js
Rewrite some more expressions like String.prototype.concat.call() or String.prototype.concat.apply() when first argument (this) is a literal
It is able to detect if all arguments in the expression are literals to skip the rewriting.
This will be useful for the new template literal rewriting process
=> Rewrite some expressions like String.prototype[concat|replace].[call|apply]("literal", ...args)

src/tests/string_method_test.rs, src/transform/binary_add_transform.rs, src/transform/call_expr_transform.rs, src/transform/function_prototype_transform.rs, src/transform/operand_handler.rs, src/visitor/ident_provider.rs, src/visitor/visitor_util.rs, test/string_method.spec.js
- Add support to spread operator in expressions like `.call`, `.apply` or direct invocations like `.concat(...a)`
To avoid executing a possible getter twice, an array is used to spread the argument first, the array is assigned to a temporary variable that is reused in the rewritten expression.
```javascript
// original
"hello".concat(...a)
// rewritten
__datadog_test_0 = "hello".concat, 
__datadog_test_1 = [...a],
_ddiast.concat(__datadog_test_0.call("hello", ...__datadog_test_1), __datadog_test_0, "hello", ...__datadog_test_1))
```
- Changes the way `.apply` calls were rewritten. Until now, they were transformed into `.call` expressions (when possible) but with the spread operator support they are kept as `.apply` expressions.
=> spread operator support

scripts/crawler.js, src/tests/mod.rs, src/tests/template_literal_test.rs, src/transform/template_transform.rs, src/visitor/csi_methods.rs, src/visitor/operation_transform_visitor.rs, src/visitor/visitor_util.rs, test/resources/tmpl-literal.js, test/template_literal.spec.js, test/tracer_logger.spec.js, test/util.js
- Takes the original template literal, extracts its arguments and creates a new expression calling the `tplOperator` taint tracking function, using a new template literal but with the new extracted variables.
```javascript
// original
const a = `Hello ${b}`
// rewritten
const a = (__datadog_test_0 = b, _ddiast.tplOperator(`Hello ${__datadog_test_0}`, __datadog_test_0))
```
- Template literal rewriting is configurable via new csi method property (the same way as the + operator):
`{ src: 'tplOperator', operator: true },`
=> Rewrite template literals as template literals

scripts/crawler.js, src/lib_wasm.rs, src/rewriter.rs, src/tests/mod.rs, src/visitor/block_transform_visitor.rs, test/initialization-prefix.spec.js, test/util.js
Add a prefix in each instrumented file to prevent crashes when the `global._ddiast` object is not initialized.
When instrumentation is done with ESM, we can not be sure that the rewrite is coming from a thread where tracer and iast are initialized.
=> Create a prefix in each instrumented file

index.d.ts, main.js, test/main.spec.js
Create a NonCacheRewriter class and export cacheRewrittenSourceMap method.
Use this in independent thread to rewrite esm files without loading the cache in this thread, and update the cache in the main thread using exported method.
=> Create a NonCacheRewriter and export cacheRewrittenSourceMap

.github/workflows/build-wasm.yml, .github/workflows/release.yml, Cargo.lock, Cargo.toml, src/transform/call_expr_transform.rs, src/transform/opt_chain_transform.rs, src/visitor/ident_provider.rs, src/visitor/visitor_util.rs
See title
I'm trying to pull in a library that depends on a much newer version of SWC.
=> update swc to v15.0.0

integration-test/stack-traces.spec.js, js/stack-trace/index.js
Fixes the stacktraces in nodejs versions >= 20
The Stack Trace generation was wrong for node 20+. In newest nodejs versions prepareStackTrace is setted (https://github.com/nodejs/node/blob/v20.x/lib/internal/bootstrap/realm.js#L462) and it executes a `toString` of each CallSite.
=> Fix stack traces when node is 20+

README.md, js/source-map/node_source_map.js, package.json
Fix wrong spellings of Node.js (wrong: NodeJS, Node.Js, Node.JS etc).
The way we spell "Node.js" is a signal about how we treat the Node.js community. By spelling the name of their language incorrectly, it could be interpreted as not caring/respecting, which obviously we do ☺️
Inspired in this [PR](https://github.com/DataDog/dd-trace-js/pull/5622)
=> Ensure correct spelling of Node.js
